Capstone
najibullahjafari/Legendary-Portfolios pull request #4
Opened 2023-05-24 19:17 UTC by najibullahjafari

#In this project:
1 - I created responsive web page that support mobile and desktop screen.
2 - I used Java Script for dynamically adding 'speaker' part to html
3 - I used of Java Script for pop up menu.

#passed all Lintes ✅

Thank you for review! 😊

2023-05-24 20:42 UTC, Efiamotu-1 requested changes
Hi @najibullahjafari , 

![](https://user-images.githubusercontent.com/89055502/221963929-dc172827-5c2c-411b-bf4d-923659f626e1.gif) 

Good job so far! 👏. Your Code is Awesome! 💪

There are some **few** issues 🐛 that you still need to work 🔧 on though to go to the next project ⏭️ but you are almost there! 🏃
## Don't Worry 🙏

It's ok to have bugs in your code 🐛. Please, see this code review as a **chance** for you to **learn** practical coding skills and learn **new tips** that can improve your code quality 💯 and help you **get a better ** 💼.

_I am going to guide you on how to fix them down below. 🤓_

## Highlights :dart: 
- ✔️ No linter Errors
- ✔️ Descriptive PR title and description
- The code is top-notch! 💯 and has a huge potential.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, don't Merge This Pull Request yet. Only Merge when it is Approved ✅.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-24 20:42 UTC, Efiamotu-1 commented on css/style.css
- [ ] The spacing between the horizontal bar and the text `main program` is not enough to match the original design, can you kindly add more spacing :+1: 
- original design
![or](https://github.com/najibullahjafari/Legendary-Portfolios/assets/89055502/d4475bd0-3169-45f1-b9df-88e5d191e3ff)

- your design
![sp](https://github.com/najibullahjafari/Legendary-Portfolios/assets/89055502/2a06991b-f975-470b-bddc-d22d2467dd05)

2023-05-24 20:42 UTC, Efiamotu-1 commented on css/style.css
- [ ] The design of the first card seems to be inconsistent with the rest thereby making the design not look so great, can you kindly work on fixing this.
- your design
![id](https://github.com/najibullahjafari/Legendary-Portfolios/assets/89055502/f28769b0-18d9-420d-a9bc-8f4e367573f6)

2023-05-24 20:42 UTC, Efiamotu-1 commented on css/style.css
- [ ] you did not provide any appropriate `alt` for the images in the highlighted section of your code please add the alt as this is important for screen readers and users of your website so that in case of a broken link they would be provided with useful information as to what the image should have been if it was displayed. :+1: 
- your `index.html` code
![alt](https://github.com/najibullahjafari/Legendary-Portfolios/assets/89055502/bd34f787-c8de-46e0-9b93-44733dbb362b)
- [ ] please ensure to also make this required additions in your `about.html` file where applicable :+1: :sparkles:

2023-05-24 20:42 UTC, Efiamotu-1 commented on css/style.css
- [ ] your logo currently does not link to your home page, please kindly work on fixing this issue :+1:

2023-05-25 00:07 UTC, najibullahjafari commented on css/style.css
hello 
I have problem with deployment.
when I deploy the css and img don't work just the html is shown.

2023-05-25 01:15 UTC, Qoosim reviewed
#  *Status: Invalid Request* :red_circle: 

Hi @najibullahjafari, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

![](https://user-images.githubusercontent.com/97100091/194103659-a0270409-def7-4972-b884-9f7c141eb90a.gif)

## Invalid Code Review Request

You have submitted a project, that 

- [ ] has conflict that need to be resolved. Kindly resolve the conflict and ask for review again.

![conflict](https://github.com/najibullahjafari/Legendary-Portfolios/assets/26597432/75d6c491-e307-446a-ad15-5c28daaaa437)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-25 01:21 UTC, najibullahjafari commented
I will solve deployment.

2023-05-25 01:45 UTC, divinecharlotte requested changes
Hi @najibullahjafari      , 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## To Highlight 💯 

- linters are passing 👍 
- Descriptive Pr 👍 




 
![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)
## Required Changes ♻️

 [ ] As requested by the previous reviewer kindly consider fixing this in your readme before requesting another review to make it professional  
1. [ ] Add a link to your Live demo section  to give a good user experience to the people visiting your readme while deploying your app put into consideration the below 
2. [ ] Kindly make sure Your "Acknowledgements" section gives an appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

_Check the comments under the review._
## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 02:22 UTC, Owusu-Desmond approved these changes
Hi @najibullahjafari , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media2.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
📌 No Linters error ✅
📌 Descriptive pull request✅
📌 Good commit messages ✅
📌 Professional README file ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limit
s policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-25 03:38 UTC, closed without merging